// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-core — see LICENSE.

// core::det self-tests. The property under test is REPRODUCIBILITY — the same bits on every row we build
// on — and that is not a property a single run can observe, so this suite tests the three things that
// CAN be observed on one machine and that together imply it:
//
//   1. THE PIN IS DOING SOMETHING. Every multiply-add in det goes through mulAdd(), whose volatile
//      temporary stops the compiler fusing it into an FMA. If that pin is ever removed, det's results
//      become whatever the row's contraction settings produce — and on this tree they are ON
//      (-ffp-contract=on, law 10), so the bits would move. The test computes the FUSED alternative
//      explicitly with std::fma (correctly rounded by IEEE everywhere, needing no FMA hardware) and
//      requires it to DIFFER from det's answer at a witness argument. A run where it does not differ is
//      reported as inconclusive rather than passed: that is the shape in which this gate would otherwise
//      quietly stop being a gate.
//   2. ACCURACY AGAINST TRUTH, not against another implementation. DetMathReference.h is generated by
//      tools/det-oracle/gen.py from mpmath at 60 digits. The system libm is kept as a SECOND oracle of a
//      different construction, at a loose bound — it cannot be the primary one, since it is the thing
//      det exists because we cannot rely on.
//   3. IDENTITIES THAT NEED NO ORACLE AT ALL. cos is even and sin is odd BIT FOR BIT; sin^2 + cos^2 is
//      within a few ulp of one. These caught what neither oracle could: a defect shared by det and by
//      every libm is invisible to any comparison between them.
//
// The arguments are not chosen for convenience — see the generator's own comment.

#include <felitronics_test.h>
#include <felitronics/core/DetMath.h>
#include "DetMathReference.h"

#include <bit>
#include <cmath>
#include <cstdint>
#include <limits>
#include <string>

namespace det = felitronics::core::det;
using felitronics::test::ok;

namespace
{
// ulp distance, sign-magnitude mapped to a monotone integer first. No long double anywhere (law 9).
std::int64_t ulps (double a, double b) noexcept
{
    auto mono = [] (double d) noexcept
    {
        const std::int64_t i = std::bit_cast<std::int64_t> (d);
        return i < 0 ? (std::int64_t) 0x8000000000000000ull - i : i;
    };
    const std::int64_t d = mono (a) - mono (b);
    return d < 0 ? -d : d;
}
double fromBits (std::uint64_t b) noexcept { return std::bit_cast<double> (b); }

// The polynomial of det::polyCos, evaluated with std::fma — i.e. exactly what the compiler would
// produce if the pin were removed and the row contracted. Kept in step with the header by hand ON
// PURPOSE: if the header's coefficients change and this is not updated, the witness check below stops
// finding a difference and the suite says INCONCLUSIVE rather than green.
double fusedPolyCos (double r) noexcept
{
    const double r2 = r * r;
    double p =  4.7794773323873853e-14;
    p = std::fma (p, r2, -1.1470745597729725e-11);
    p = std::fma (p, r2,  2.0876756987868099e-09);
    p = std::fma (p, r2, -2.7557319223985893e-07);
    p = std::fma (p, r2,  2.4801587301587302e-05);
    p = std::fma (p, r2, -1.3888888888888889e-03);
    p = std::fma (p, r2,  4.1666666666666666e-02);
    p = std::fma (p, r2, -5.0000000000000000e-01);
    return std::fma (r2, p, 1.0);
}
} // namespace

int main()
{
    // ---------- 1. the pin is load-bearing ----------
    {
        int witnesses = 0;
        double worstArg = 0.0;
        for (int i = 1; i <= 20000; ++i)
        {
            const double r = 0.7853981633974483 * (double) i / 20000.0;   // (0, pi/4]
            if (std::bit_cast<std::uint64_t> (det::detail::polyCos (r))
                != std::bit_cast<std::uint64_t> (fusedPolyCos (r)))
            { ++witnesses; if (worstArg == 0.0) worstArg = r; }
        }
        ok (witnesses > 0, "pin: the fused alternative differs from the pinned one at "
                           + std::to_string (witnesses) + " of 20000 arguments"
                           + (witnesses == 0 ? "  — INCONCLUSIVE, this gate is not testing anything" : ""));
        // and the pinned one is what det actually calls
        ok (std::bit_cast<std::uint64_t> (det::cos (worstArg))
            == std::bit_cast<std::uint64_t> (det::detail::polyCos (worstArg)),
            "pin: det::cos routes through the pinned polynomial on the first quadrant");
    }

    // ---------- 2. against correctly rounded truth ----------
    {
        std::int64_t worstCos = 0, worstSin = 0;
        for (int i = 0; i < det::reference::kTableSize; ++i)
        {
            const auto& row = det::reference::kTable[i];
            const double x = fromBits (row.arg);
            const std::int64_t uc = ulps (det::cos (x), fromBits (row.cosv));
            const std::int64_t us = ulps (det::sin (x), fromBits (row.sinv));
            if (uc > worstCos) worstCos = uc;
            if (us > worstSin) worstSin = us;
        }
        ok (det::reference::kTableSize >= 100, "oracle: the table is non-trivial ("
                                               + std::to_string (det::reference::kTableSize) + " arguments)");
        ok (worstCos <= 2, "oracle: det::cos within " + std::to_string (worstCos) + " ulp of the correctly rounded value");
        ok (worstSin <= 2, "oracle: det::sin within " + std::to_string (worstSin) + " ulp of the correctly rounded value");
    }

    // ---------- 3. identities that need no oracle ----------
    {
        std::uint64_t st = 0xfeedfacecafebeefull;
        long badEven = 0, badOdd = 0; std::int64_t worstPyth = 0;
        const long kN = 300000;
        for (long i = 0; i < kN; ++i)
        {
            st ^= st << 13; st ^= st >> 7; st ^= st << 17;
            const double x = ((double) (st >> 11) / 9007199254740992.0) * 4.0 * 3.14159265358979323846
                             - 2.0 * 3.14159265358979323846;
            if (std::bit_cast<std::uint64_t> (det::cos (-x)) != std::bit_cast<std::uint64_t> (det::cos (x))) ++badEven;
            if (std::bit_cast<std::uint64_t> (det::sin (-x)) != std::bit_cast<std::uint64_t> (-det::sin (x))) ++badOdd;
            const double s = det::sin (x), c = det::cos (x);
            const std::int64_t u = ulps (s * s + c * c, 1.0);
            if (u > worstPyth) worstPyth = u;
        }
        ok (badEven == 0, "identity: cos is even BIT FOR BIT (" + std::to_string (badEven) + " of " + std::to_string (kN) + " differ)");
        ok (badOdd  == 0, "identity: sin is odd BIT FOR BIT ("  + std::to_string (badOdd)  + " of " + std::to_string (kN) + " differ)");
        ok (worstPyth <= 4, "identity: sin^2 + cos^2 within " + std::to_string (worstPyth) + " ulp of one");
    }

    // ---------- 4. the system libm as a SECOND, loose oracle of a different construction ----------
    {
        std::uint64_t st = 0x0123456789abcdefull;
        std::int64_t worst = 0;
        for (long i = 0; i < 200000; ++i)
        {
            st ^= st << 13; st ^= st >> 7; st ^= st << 17;
            const double x = ((double) (st >> 11) / 9007199254740992.0) * 4.0 * 3.14159265358979323846
                             - 2.0 * 3.14159265358979323846;
            worst = std::max (worst, std::max (ulps (det::cos (x), std::cos (x)), ulps (det::sin (x), std::sin (x))));
        }
        ok (worst <= 4, "second oracle: det agrees with this row's libm to " + std::to_string (worst) + " ulp");
    }

    // ---------- 5. the domain is refused, not guessed ----------
    {
        const double big = 16777216.0;                                   // 2^24, the stated limit
        ok (std::isnan (det::cos (big)) && std::isnan (det::sin (big)), "domain: 2^24 is refused with NaN");
        ok (std::isnan (det::cos (-big)) && std::isnan (det::sin (-big)), "domain: -2^24 is refused");
        ok (! std::isnan (det::cos (std::nextafter (big, 0.0))), "domain: just inside the limit is answered");
        ok (std::isnan (det::cos (std::numeric_limits<double>::quiet_NaN())), "domain: NaN in, NaN out");
        ok (std::isnan (det::cos (std::numeric_limits<double>::infinity())), "domain: infinity is refused");
        ok (std::bit_cast<std::uint64_t> (det::cos (0.0)) == std::bit_cast<std::uint64_t> (1.0), "domain: cos(0) is exactly 1");
        ok (std::bit_cast<std::uint64_t> (det::sin (0.0)) == std::bit_cast<std::uint64_t> (0.0), "domain: sin(0) is exactly +0");
    }

    // ---------- 6. THE UNSAFE-MATH TRIPWIRE, which no #if can be ----------
    // DetMath.h refuses to compile under -ffast-math and, on gcc, under -funsafe-math-optimizations,
    // because reassociation rewrites its Dekker splits and polynomial accumulations into algebraically
    // equal, numerically different forms. Measured over 100000 points of det::pow10:
    //
    //     flag                          clang/arm64          gcc 14 x86-64
    //     (none)                        2253cf954ae4dc64     2253cf954ae4dc64
    //     -ffp-contract=fast            2253cf954ae4dc64     2253cf954ae4dc64   <- the volatile pin holds
    //     -ffast-math                   c2c77b419859ee6b     694fb75fe048f32a   <- broken, differently
    //     -funsafe-math-optimizations   bee2675b81d4fcd3     (same class)
    //
    // THE HOLE THE #error CANNOT CLOSE: clang defines NO macro for a bare -funsafe-math-optimizations
    // (measured — the only one it moves is __FINITE_MATH_ONLY__, to 0, which is also its default), and
    // clang is both the developer's row and the wasm toolchain. So the preprocessor cannot see that case
    // and this runtime check is what does. It is two assertions on purpose:
    //   · within 2 ulp of the CORRECTLY ROUNDED value (Python's decimal at 60 digits, an oracle computed
    //     outside this tree) — that is the accuracy claim, and it is what a wrong answer violates;
    //   · equal to a PINNED bit pattern — that is the flag claim. A build whose flags have quietly
    //     rewritten this arithmetic still lands near the right answer; it just stops landing on the same
    //     double as every other row, which is the entire property det:: exists to provide.
    {
        // TWO reference tables, because they are two different claims and collapsing them is wrong —
        // the first draft of this test used the oracle as the pin and failed at once, correctly: det is
        // within 2 ulp of correctly rounded, not equal to it, and at 10^0.6 it is exactly 1 ulp off.
        struct Ref { double x; std::uint64_t rounded; std::uint64_t det; };
        static const Ref refs[] = {
            //  x        correctly rounded      what det:: returns
            { -3.0,  0x3f50624dd2f1a9fcull, 0x3f50624dd2f1a9fcull },
            { -1.15, 0x3fb21f97ef20893cull, 0x3fb21f97ef20893cull },
            { 0.6,   0x400fd93c1f526ddfull, 0x400fd93c1f526de0ull },   // 1 ulp — det's stated accuracy, not a fault
            { -6.0,  0x3eb0c6f7a0b5ed8dull, 0x3eb0c6f7a0b5ed8dull },
            { 2.5,   0x4073c3a4edfa9759ull, 0x4073c3a4edfa9759ull },
            { -0.05, 0x3fec8520affa0a4bull, 0x3fec8520affa0a4bull },
        };
        // The `rounded` column is Python's decimal at 90 digits, computed from `Decimal.from_float(x)` —
        // THE BINARY64 ARGUMENT THE CALL ACTUALLY RECEIVES, not the decimal literal it was written as.
        // Those are different numbers and the first draft used the wrong one: it made 10^-1.15 look 1 ulp
        // wrong when det is correctly rounded there, and hid that the 1-ulp case is 10^0.6. An oracle read
        // at a different input than the code under test is not an oracle.
        // The `det` column was captured from Apple clang/arm64, gcc 14/glibc x86-64 and emcc/musl wasm32,
        // which returned THE SAME BITS at all six points; that agreement is what makes it a pin on the
        // build's flags rather than a photograph of one machine.
        int worst = 0, moved = 0;
        for (const auto& r : refs)
        {
            const std::uint64_t gb = std::bit_cast<std::uint64_t> (det::pow10 (r.x));
            const std::int64_t d = (std::int64_t) gb - (std::int64_t) r.rounded;
            const int ulp = (int) (d < 0 ? -d : d);
            if (ulp > worst) worst = ulp;
            if (gb != r.det) ++moved;
        }
        ok (worst <= 2, "oracle: det::pow10 within " + std::to_string (worst)
                        + " ulp of the correctly rounded value at 6 points");
        ok (moved == 0, "pinned: det::pow10 returns the reference bits at those 6 points");

        // AND THE DENSE PIN, because six points is not a pin. An adversarial round dropped the `volatile`
        // from ONE step of exp2Frac — the single likeliest wrong edit in this file, since it reads as a
        // tidy-up — and det::pow10 changed across 100000 arguments while all six points above still
        // matched. A sparse pin tests the six values somebody happened to choose; this tests the function.
        //
        // THE ARGUMENTS ARE BUILT FROM INTEGERS, exactly. `(i - N/2) / 4096.0` is representable for every
        // i, so the argument stream is identical on every row BY CONSTRUCTION — where a sweep written as
        // `lo + i * step` would be a contractible multiply-add and would make arm64 and a non-FMA x86-64
        // build disagree about the INPUT. That mistake was made once here already, and it looked exactly
        // like det:: being non-portable.
        //
        // The eight values below were captured on Apple clang/arm64, gcc 14/glibc x86-64 (-march=native,
        // contraction live) and emcc/musl wasm32, which returned the same eight.
        {
            auto mix = [] (std::uint64_t h, double v)
            { return (h ^ std::bit_cast<std::uint64_t> (v)) * 1099511628211ull; };
            const int N = 100000;
            std::uint64_t hCos = 1469598103934665603ull, hSin = hCos, hTan = hCos,
                          hL2 = hCos, hL10 = hCos, hE2 = hCos, hP10 = hCos, hPow = hCos;
            for (int i = 0; i < N; ++i)
            {
                const double t  = (double) (i - N / 2) / 4096.0;
                const double u  = (double) (i + 1) / 8192.0;
                const double db = (double) (i - N / 2) / 512.0;
                hCos = mix (hCos, det::cos (t));   hSin = mix (hSin, det::sin (t));
                hTan = mix (hTan, det::tan (t));   hL2  = mix (hL2,  det::log2 (u));
                hL10 = mix (hL10, det::log10 (u)); hE2  = mix (hE2,  det::exp2 (t));
                hP10 = mix (hP10, det::pow10 (db / 20.0));
                hPow = mix (hPow, det::pow (u, t));
            }
            struct Pin { const char* name; std::uint64_t got, want; };
            const Pin pins[] = {
                { "cos",   hCos, 0x7d4385d092968bb2ull }, { "sin",   hSin, 0x15d3bf218d00b6acull },
                { "tan",   hTan, 0x4539178d5ff966abull }, { "log2",  hL2,  0x1bbdfc745d669ce7ull },
                { "log10", hL10, 0x74abd6c9f016d15dull }, { "exp2",  hE2,  0x390f967aca102148ull },
                { "pow10", hP10, 0x90d3565674dd9a20ull }, { "pow",   hPow, 0xb2d816ef180685ecull },
            };
            int drift = 0;
            for (const auto& q : pins)
                if (q.got != q.want)
                {
                    ++drift;
                    std::printf ("      det::%-6s over %d arguments: %016llx, pinned %016llx\n",
                                 q.name, N, (unsigned long long) q.got, (unsigned long long) q.want);
                }
            ok (drift == 0, drift == 0
                  ? "dense pin: all eight det:: functions reproduce their reference checksum over 100000 arguments"
                  : std::to_string (drift) + " of 8 det:: functions DRIFTED over 100000 arguments. Either this "
                    "build has unsafe-math flags (clang defines no macro for a bare -funsafe-math-optimizations "
                    "off ARM, so the #error cannot see that one), or an edit to DetMath.h changed what it "
                    "computes — check that every multiply-add still goes through mulAdd()/mul().");
        }
    }

    return felitronics::test::report();
}
