#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-core — see LICENSE.
"""
Generates the reference table core::det is tested against: DetMathReference.h.

WHY A GENERATED TABLE AND NOT A COMPARISON WITH THE SYSTEM libm. The system libm is not the truth — it is
the very thing core::det exists because we cannot rely on. It stays in the suite as a SECOND, loose oracle
(a different construction, which is what the project's fixture rules ask for), but the bound in ulp is
measured against correctly rounded values computed here at 60 decimal digits with mpmath.

WHY THE ARGUMENTS ARE NOT ROUND NUMBERS. A table of arguments the author found convenient certifies the
arguments, not the function. This one holds, per function:
  · every argument class the library actually evaluates (window arguments, twiddle seeds),
  · the neighbourhood of every multiple of pi/2, where argument reduction is hardest and where the first
    draft of DetMath.h was wrong by 1.6e11 ulp,
  · the worst arguments found by an offline adversarial scan (hunt.cpp) rather than chosen,
  · the domain edges and the refusal set.

Run:  python3 tools/det-oracle/gen.py > modules/core/tests/DetMathReference.h
Requires mpmath (pip install mpmath). The version used is recorded in the output.
"""
import struct
import sys

from mpmath import mp, mpf, cos, sin, pi
import mpmath

mp.dps = 60

def bits(x: float) -> int:
    return struct.unpack('<Q', struct.pack('<d', x))[0]

def cr(f, x: float) -> float:
    """correctly rounded f(x) as a double"""
    return float(f(mpf(x)))

def near(x: float, steps=(-2, -1, 0, 1, 2)):
    """x and its immediate float neighbours, walking the sign-magnitude representation correctly
    (a naive +-1 on the bit pattern underflows at zero and jumps the sign at the boundary)."""
    out = []
    for s in steps:
        out.append(float(mpmath.nstr(x, 30)) if s == 0 else _step(x, s))
    return [v for v in out if v is not None]

def _step(x: float, n: int):
    import math
    v = x
    for _ in range(abs(n)):
        v = math.nextafter(v, math.inf if n > 0 else -math.inf)
    return v

args = []

# the window's own arguments at order 14, every 97th (a prime stride, so the sample is not periodic
# with any quadrant boundary), plus the quadrant boundaries themselves
N = 1 << 14
for i in list(range(0, N // 4 + 1, 97)) + [0, N // 8, N // 4]:
    args.append(2.0 * float(pi) * i / N)

# the twiddle seeds: -2*pi/2^k for every transform size the library permits
for k in range(1, 23):
    args.append(-2.0 * float(pi) / (1 << k))

# the hard neighbourhood: every multiple of pi/2 in range, and its immediate float neighbours
for m in range(-4, 5):
    args.extend(near(m * float(pi) / 2.0))

# domain edges and the refusal set are handled separately in the test; here only finite in-domain values
seen, uniq = set(), []
for a in args:
    if abs(a) >= 16777216.0:
        continue
    b = bits(a)
    if b in seen:
        continue
    seen.add(b)
    uniq.append(a)

print("// SPDX-License-Identifier: AGPL-3.0-or-later")
print("// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-core — see LICENSE.")
print("//")
print("// GENERATED by tools/det-oracle/gen.py — do not edit by hand, regenerate.")
print(f"// mpmath {mpmath.__version__} at {mp.dps} decimal digits. Each row is an argument and the CORRECTLY")
print("// ROUNDED value of the function at it, as raw IEEE-754 bit patterns: no decimal round-trip, no")
print("// hex-float parsing difference between five compilers, and no long double anywhere (law 9).")
print("")
print("#pragma once")
print("")
print("#include <cstdint>")
print("")
print("namespace felitronics::core::det::reference")
print("{")
print("")
print("struct Row { std::uint64_t arg, cosv, sinv; };")
print("")
print(f"inline constexpr Row kTable[] = {{   // {len(uniq)} arguments")
for a in uniq:
    print(f"    {{ 0x{bits(a):016x}ull, 0x{bits(cr(cos, a)):016x}ull, 0x{bits(cr(sin, a)):016x}ull }},")
print("};")
print("")
print(f"inline constexpr int kTableSize = {len(uniq)};")
print("")
print("} // namespace felitronics::core::det::reference")
